### PR TITLE
Add integration test

### LINKED ISSUE #162: Integration Tests
Add some integration/driver tests.

### PR DESCRIPTION
**Pull request by thevirtuoso1973**
Closes #162. Maybe see if you can run the tests with iOS emulator/device following the added instruction in the README.md. It's not a huge problem if you can't cos this is more platform specific, and is just a bonus (*widget* tests are the real bread and butter).

@saachipahwa But **definitely check if you can build/run the app normally on iOS**, I had to change the Android build just to get the normal app to run after adding the integration_test library.

https://user-images.githubusercontent.com/46009390/109393978-860d5d00-791c-11eb-98c0-afa96c6547c0.mp4

### CODE REVIEW

**Comment by saachipahwa** [comment]
image
image

**Comment by thevirtuoso1973** [comment]
@saachipahwa Can you `git bisect` from the integration test branch to see which commit introduced that Icon?

**Comment by saachipahwa** [comment]
This is the commit 
image

**Comment by thevirtuoso1973** [comment]
@saachipahwa Ok can you checkout develop and just add this package https://pub.dev/packages/integration_test to pubspec.yaml. Then run and see if it works as expected.

**Comment by saachipahwa** [comment]
There's no question marks when i add the package to develop and run

**Comment by thevirtuoso1973** [comment]
Cool I think I know what the problem is then.

**Comment by saachipahwa** [comment]
No more question marks!

**Pull request merged**
