### PR TITLE
Fix deprecation - use ScaffoldMessenger

### LINKED ISSUE #179: Fix deprecated warnings

### PR DESCRIPTION
**Pull request by thevirtuoso1973**
Close #179.

The notable change is in sharing page, where I insert a ScaffoldMessenger to fix the snackbar bug.
I've removed using keys to scaffolds, we don't seem to need them anymore.

### CODE REVIEW

**Comment by thevirtuoso1973** [comment]
Something broke after updating flutter, hacky fix would be rolling back version, but I'll try to figure it out properly first.

**Comment by thevirtuoso1973** [comment]
Provider's library seems to have broke.

**Comment by saachipahwa** [comment]
I had already started on a different branch this morning, sorry

**Comment by thevirtuoso1973** [comment]
Alright, I'm going to use my one. Also because I'm going to change how we call snackbars slightly.

**Review by saachipahwa — APPROVED** [review]

**Pull request merged**
