### PR TITLE
Add Android launch screen

### LINKED ISSUE #142: Launch screen

### PR DESCRIPTION
**Pull request by thevirtuoso1973**
Replace logo.png (see the added file in this PR) with another png of the same name to change the launch screen.
Resolves #142.

### CODE REVIEW

**Comment by saachipahwa** [comment]
Didn't seem to be working on the android 10 device but can you test it on yours

**Comment by thevirtuoso1973** [comment]
Ok so did you try replacing the image? (I've assigned this to you if that wasn't clear.)

**Comment by saachipahwa** [comment]
Yes, i did. Ok i'll just resize the logo in the image, I was wondering if there was a way to make the entire pic smaller

**Comment by saachipahwa** [comment]
looks better now!

**Pull request merged**
